bases:
  - ../calico
resources:
- configMap.yaml
vars:
  - name: CALICO_IPV6POOL_CIDR
    objref:
      name: calico-custom.conf
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.IPV6podCIDR
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: calico-node
      namespace: kube-system
    path: custom.patch.json
