apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit-es
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit-es
