apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-es
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit-es
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-es
  labels:
    app.kubernetes.io/name: fluent-bit-es
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-es
  labels:
    app.kubernetes.io/name: fluent-bit-es
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluent-bit-es
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluent-bit-es
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-es
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit-es
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit-es
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit-es
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: system-node-critical
      serviceAccountName: fluent-bit-es
      containers:
      - name: fluent-bit
        image: "cr.fluentbit.io/fluent/fluent-bit:2.1.2"
        # imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 2020
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch-logging"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        # https://github.com/fluent/fluent-bit/issues/497
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      # - operator: "Exists"
      #   effect: "NoExecute"
      # - operator: "Exists"
      #   effect: "NoSchedule"
