kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: http
    name: http

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: minio
        imagePullPolicy: IfNotPresent
        image: minio/minio:RELEASE.2021-01-30T00-20-58Z
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: minio-access-key
              name: minio-secret
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: minio-secret-key
              name: minio-secret
        - name: MINIO_REGION
          value: us-east-1
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_WORM
          value: "off"
        - name: MINIO_DOMAIN
          value: "minio.t.khs1994.com"
        args:
          - server
          - /data
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: http
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: http
            scheme: HTTP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio
