kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: http
    name: http
  - port: 9090
    targetPort: console
    name: console

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: minio
        imagePullPolicy: IfNotPresent
        image: minio/minio:RELEASE.2022-10-24T18-35-07Z
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 9090
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: minio-root-user
              name: minio-credentials
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: minio-root-password
              name: minio-credentials
        - name: MINIO_REGION_NAME
          value: us-east-1
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_DOMAIN
          value: "minio.t.khs1994.com"
        args:
          - server
          - /data
          - --console-address
          - ':9090'
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: http
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: http
            scheme: HTTP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio
