resources:
- calico.yaml
- configMap.yaml
- csi-driver.yaml
vars:
  - name: CALICO_IPV4POOL_CIDR
    objref:
      name: calico.conf
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.podCIDR
  - name: CALICO_IPV4POOL_IPIP
    objref:
      name: calico.conf
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.ipip
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: calico-node
      namespace: kube-system
    path: basic.patch.json
