resources:
- calico.yaml
- configMap.yaml
- csi-driver.yaml
vars:
  - name: CALICO_IPV4POOL_CIDR
    objref:
      name: calico.conf
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.podCIDR
  - name: CALICO_IPV4POOL_IPIP
    objref:
      name: calico.conf
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.ipip
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: calico-node
      namespace: kube-system
    path: basic.patch.json
images:
- name: docker.io/calico/cni
  newName: ghcr.io/khs1994-docker/docker.io/calico/cni
- name: docker.io/calico/node
  newName: ghcr.io/khs1994-docker/docker.io/calico/node
- name: docker.io/calico/kube-controllers
  newName: ghcr.io/khs1994-docker/docker.io/calico/kube-controllers
- name: calico/csi
  newName: ghcr.io/khs1994-docker/docker.io/calico/csi
- name: calico/node-driver-registrar
  newName: ghcr.io/khs1994-docker/docker.io/calico/node-driver-registrar
