apiVersion: node.k8s.io/v1 # RuntimeClass is defined in the node.k8s.io API group
# RuntimeClass is a non-namespaced resource
kind: RuntimeClass
metadata:
  name: runc  # The name the RuntimeClass will be referenced by
# handler: myconfiguration  # The name of the corresponding CRI configuration
handler: runc # 值与 CRI 配置文件对应

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runcv1
handler: runcv1

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runclinux
handler: runclinux

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun
handler: crun

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun-disable-systemd
handler: crun-disable-systemd

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runsc
handler: runsc

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runsc-kvm
handler: runsc-kvm

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-qemu
handler: kata-qemu

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-fc
handler: kata-fc
