

services:
  nfs:
    restart: "no"
    image: erichough/nfs-server
    # https://github.com/ehough/docker-nfs-server/pull/56
    # image: klutchell/nfs-server
    volumes:
      - ./exports.txt:/etc/exports
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs:/nfs
      - ${APP_ROOT:-../app}:/nfs/lnmp/app
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/mysql:/nfs/lnmp/mysql
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/redis:/nfs/lnmp/redis
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/registry:/nfs/lnmp/registry
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/log:/nfs/lnmp/log
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/kubernetes_nfs_pv:/nfs/kubernetes_nfs_pv
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/kubernetes_nfs_csi:/nfs/kubernetes_nfs_csi
      - /lib/modules:/lib/modules:ro
    environment:
    - NFS_DISABLE_VERSION_3=${NFS_DISABLE_VERSION_3:-1}
    - TZ=${TZ:-Asia/Shanghai}
    - NFS_LOG_LEVEL=${NFS_LOG_LEVEL:-debug}
    cap_add:
     - SYS_ADMIN
     - SYS_MODULE
    privileged: true
    ports:
      # - "111:111"
      # - "111:111/udp"
      # nfs4 only need open 2049/tcp port
      - "2049:2049"
      # - "2049:2049/udp"
      # - "32765:32765"
      # - "32765:32765/udp"
      # - "32767:32767"
      # - "32767:32767/udp"

volumes:
  nfs-volume:
