# 可以理解为计划任务，可以运行 Laravel 调度器 Schedule

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lnmp-cron
  labels:
    app: lnmp
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # 指定可以保留多少完成和失败的 Job。
          successfulJobsHistoryLimit: 0
          failedJobsHistoryLimit: 0
          suspend: false
          # 并发策略
          concurrencyPolicy: Forbid # Allow Replace
          # startingDeadlineSeconds: 0
          containers:
          - name: lnmp-cron
            image: khs1994/php:8.4.10-cli-alpine
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            # - date; echo Hello from the Kubernetes cluster
            - php /app/laravel/artisan schedule:run
            volumeMounts:
            - name: lnmp-app
              mountPath: /app
          volumes:
          - name: lnmp-app
            persistentVolumeClaim:
              claimName: lnmp-app
          restartPolicy: Never # OnFailure
