apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  labels:
    app: registry
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: registry
      env: development
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath # hostpath | slow
