resources:
- apiservice.yaml
- deployment.yaml
- rbac.yaml
- service.yaml
commonLabels:
  k8s-app: metrics-server
images:
  - name: registry.k8s.io/metrics-server/metrics-server:v0.8.0
    newName: ghcr.io/khs1994-docker/registry.k8s.io/metrics-server/metrics-server
