# MySQL statefulSet 类型的定义文件

kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  selector:
    app: lnmp
    tier: mysql
  ports:
    - port: 3306
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  serviceName: mysql
  # podManagementPolicy: "Parallel" # 并行创建或删除 Pod
  # podManagementPolicy: "OrderedReady" # default 按照 Pod 的次序依次创建每个 Pod 并等待 Ready 之后才创建后面的 Pod
  replicas: 1
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
  template:
    metadata:
      labels:
        app: lnmp
        tier: mysql
      # annotations:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - name: lnmp-mysql
        imagePullPolicy: IfNotPresent
        image: mysql:8.0.25
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: lnmp-mysql-data
          mountPath: /var/lib/mysql
        # - name: lnmp-mysql-cnf
        #   mountPath: /etc/mysql/conf.d/docker.cnf
        #   subPath: docker.cnf
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lnmp-mysql-password
              key: password
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: lnmp-tz
              key: TZ
        - name: MYSQL_DATABASE
          value: test
  volumeClaimTemplates:
  - metadata:
      name: lnmp-mysql-data
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 20Gi
      selector:
        matchLabels:
          app: lnmp
          tier: mysql
      storageClassName: slow
