resources:
- ../../../base
configMapGenerator:
- name: lnmp-redis-conf
  files:
  - redis.conf=config/redis.development.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
generatorOptions:
  labels:
    app: lnmp
    tier: redis
  disableNameSuffixHash: true
images:
- name: redis
  newName: ghcr.io/khs1994-docker/docker.io/library/redis
