resources:
  - ../base
images:
  - name: ghcr.io/dpsigs/klutchell-nfs-server
    newName: docker.cnb.cool/khs1994-docker/khs1994/klutchell-nfs-server
  - name: ghcr.io/khs1994-docker/library/busybox
    newName: docker.cnb.cool/khs1994-docker/library/busybox
