kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  selector:
    app: lnmp
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
  replicas: 1
  # 新创建的 Pod 状态为 Ready 持续的时间至少为多少秒才认为 Pod Available(Ready)。
  minReadySeconds: 5
  revisionHistoryLimit: 5 # 保留几个版本
  strategy:
    type: RollingUpdate # Recreate
    rollingUpdate:
      # 可以为整数或者百分比，默认为 desired Pods数的 25%.
      # Scale Up 新的 ReplicaSet 时，按照比例计算出允许的 MaxSurge，计算时向上取整(比如 3.4，取4)。
      # 滚动升级时会先启动 1 个 pod
      maxSurge: 1
      # 可以为整数或者百分比，默认为 desired Pods数的25%.
      # Scale Down 旧的 ReplicaSet 时，按照比例计算出允许的 maxUnavailable，计算时向下取整(比如 3.6，取3)。
      # 滚动升级时允许的最大 Unavailable 的 pod 个数
      maxUnavailable: 1
  template:
    metadata:
      labels:
        # https://kubernetes.io/zh/docs/concepts/overview/working-with-objects/common-labels/
        # app.kubernetes.io/name: mysql
        # app.kubernetes.io/instance: lnmp-xxx
        # app.kubernetes.io/version: 8.0.25
        # app.kubernetes.io/component: database
        # app.kubernetes.io/part-of: lnmp
        # app.kubernetes.io/managed-by: helm
        app: lnmp
        tier: mysql
        # track: stable # canary
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      # imagePullSecrets:
      # initContainers:
      #   - name: "remove-lost-found"
      #     image: "busybox"
      #     command: ["rm", "-fr", "/var/lib/mysql/lost+found"]
      #     volumeMounts:
      #     - name: data
      #       mountPath: /var/lib/mysql
      # restartPolicy: Never # Always、OnFailure 和 Never
      containers:
      - name: lnmp-mysql
        image: mysql:8.0.25
        imagePullPolicy: IfNotPresent
        # resources:
        # envFrom:
        #   - configMapKeyRef:
        #       name: env-config
        env:
        # 将 secret 变为环境变量
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lnmp-mysql-password
              key: password
        # config 用作环境变量
        - name: TZ
          valueFrom:
             configMapKeyRef:
               name: lnmp-tz
               key: TZ
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: mysql
        # livenessProbe:
        #   exec:
        #     command:
        #       no password
        #       - mysqladmin
        #       - ping
        #
        #       - sh
        #       - -c
        #       - "mysqladmin ping -u root -p${MYSL_ROOT_PASSWORD}"
        #   initialDelaySeconds:
        #   periodSeconds:
        #   timeoutSeconds:
        #   successThreshold:
        #   failureThreshold:
        # readinessProbe:
        #   exec:
        #     command:
        #     # 同上
        volumeMounts:
        - name: lnmp-mysql-data
          mountPath: /var/lib/mysql
        - name: lnmp-mysql-cnf
          mountPath: /etc/mysql/conf.d/docker.cnf
          subPath: docker.cnf
        # - name: lnmp-mysql-log
        #   mountPath: /var/log/mysql
      volumes:
      # - name: lnmp-mysql-log
      #   hostPath:
      #     path: /var/log/mysql
      - name: lnmp-mysql-data
        persistentVolumeClaim:
          claimName: lnmp-mysql-data
      - name: lnmp-mysql-cnf
        configMap:
          name: lnmp-mysql-cnf
          items:
          - key: docker.cnf
            path: docker.cnf
