apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    app.kubernetes.io/name: kube-scheduler #与servicemonitor中的selector匹配
spec:
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
subsets:
  - addresses:
    - ip: 192.168.199.100
    ports:
      - name: https-metrics
        port: 10259
