resources:
- deploy.yaml
images:
  - name: k8s.gcr.io/ingress-nginx/controller:v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c303899
    newName: ccr.ccs.tencentyun.com/khs1994/nginx-ingress-controller
    newTag: v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c303899
patchesJson6902:
  - path: port.patch.json
    target:
      kind: Service
      name: ingress-nginx-controller
      version: v1
      namespace: ingress-nginx
      group: ""
