resources:
- deploy.yaml
images:
  - name: k8s.gcr.io/ingress-nginx/controller:v0.41.2@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de
    newName: ccr.ccs.tencentyun.com/khs1994/nginx-ingress-controller
    newTag: v0.41.2@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de
patchesJson6902:
  - path: port.patch.json
    target:
      kind: Service
      name: ingress-nginx-controller
      version: v1
      namespace: ingress-nginx
      group: ""
