resources:
- deploy.yaml
images:
  - name: k8s.gcr.io/ingress-nginx/controller:v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713
    newName: ccr.ccs.tencentyun.com/khs1994/nginx-ingress-controller
    newTag: v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713
patchesJson6902:
  - path: port.patch.json
    target:
      kind: Service
      name: ingress-nginx-controller
      version: v1
      namespace: ingress-nginx
      group: ""
