resources:
- deploy.yaml
images:
  - name: k8s.gcr.io/ingress-nginx/controller:v0.40.2@sha256:46ba23c3fbaafd9e5bd01ea85b2f921d9f2217be082580edc22e6c704a83f02f
    newName: ccr.ccs.tencentyun.com/khs1994/nginx-ingress-controller
    newTag: v0.40.2@sha256:46ba23c3fbaafd9e5bd01ea85b2f921d9f2217be082580edc22e6c704a83f02f
patchesJson6902:
  - path: port.patch.json
    target:
      kind: Service
      name: ingress-nginx-controller
      version: v1
      namespace: ingress-nginx
      group: ""
