apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      # 修改 ip 地址池和集群节点(node)网段相同
      # wsl2 每次重启请重新 apply 此配置
      # 网段到 网络适配器 wsl2 查看
      # 第三位 +5 以内，不要与 wsl2 重复
      - 172.23.69.1/28
