# commonLabels:
#   app: lnmp
# commonAnnotations:
#   app: lnmp
resources:
  - ../../base
configMapGenerator:
- name: lnmp-mysql-cnf
  files:
  - docker.cnf=config/docker.development.cnf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
secretGenerator:
- name: lnmp-mysql-password
  literals:
  - password=mytest
generatorOptions:
  labels:
    app: lnmp
    tier: mysql
  disableNameSuffixHash: true
