resources:
- ../../base
- ../../../config/secret
configMapGenerator:
- name: lnmp-nginx-conf
  files:
  - nginx.conf=config/nginx.production.conf
- name: lnmp-nginx-conf.d
  files:
  - config/conf.d/t.khs1994.com.production.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
generatorOptions:
  labels:
    app: lnmp
    tier: nginx
